/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_aim_mainagent_CEventAgentAdapter */

#ifndef _Included_org_aim_mainagent_CEventAgentAdapter
#define _Included_org_aim_mainagent_CEventAgentAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_aim_mainagent_CEventAgentAdapter
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_aim_mainagent_CEventAgentAdapter_init
  (JNIEnv *, jclass);

/*
 * Class:     org_aim_mainagent_CEventAgentAdapter
 * Method:    activateMonitorEvents
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_aim_mainagent_CEventAgentAdapter_activateMonitorEvents
  (JNIEnv *, jclass);

/*
 * Class:     org_aim_mainagent_CEventAgentAdapter
 * Method:    deactivateMonitorEvents
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_aim_mainagent_CEventAgentAdapter_deactivateMonitorEvents
  (JNIEnv *, jclass);

/*
 * Class:     org_aim_mainagent_CEventAgentAdapter
 * Method:    printlnNonBlocking
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_aim_mainagent_CEventAgentAdapter_printlnNonBlocking
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
